# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests to the develop branch
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies in the client folder
      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      # Ensure correct permissions for ESLint
      - name: Set permissions for node_modules
        run: chmod +x ./client/node_modules/.bin/eslint

      # Run lint
      - name: Run Lint
        run: npx eslint client/src --report-unused-disable-directives --max-warnings 0


      # Run build
      - name: Run Build
        run: npm run build
        working-directory: ./client

      # Run Cypress component tests
      - name: Run Cypress Component Tests
        run: npm run cypress:run   # <-- uses the "cypress:run" script we confirmed
        working-directory: ./client