# Name of workflow
name: Lint and Test Workflow

# Trigger workflow on all pull requests to the develop branch
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install dependencies in the client folder
      - name: Install Client Dependencies
        run: npm install
        working-directory: ./client

      # Set permissions for ESLint
      - name: Set permissions for ESLint
        run: chmod +x ./client/node_modules/.bin/eslint

      # Set permissions for Vite
      - name: Set permissions for Vite
        run: chmod +x ./client/node_modules/.bin/vite 
        
      # Set permissions for Cypress before install
      - name: Set permissions for Cypress Binary
        run: chmod +x ./client/node_modules/.bin/cypress

      # Install Cypress binary
      - name: Install Cypress Binary
        run: npx cypress install
        working-directory: ./client

      # Set permissions for Cypress after install
      - name: Set permissions for Cypress
        run: chmod +x ./client/node_modules/.bin/cypress  

      # Run lint
      - name: Run Lint
        run: npm run lint
        working-directory: ./client

      # Run build
      - name: Run Build
        run: npm run build
        working-directory: ./client

      # Run Cypress component tests
      - name: Run Cypress Component Tests
        run: npx cypress run --component   
        working-directory: ./client